version: "3.8"
services:
  db:
    ports:
      - "5432:5432"
    build: ./database
  web:
    build: .
    ports:
      - "5000:80"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:8080"

